workflows:
  ios-simple-workflow:
    name: iOS Simple Workflow
    environment:
      xcode: 14.3 # Cambia esto a la versión específica que prefieras o usa "latest"
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Compilar el Proyecto
        script: |
          xcodebuild -project YourApp.xcodeproj \
                     -scheme YourAppScheme \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
                     clean build
    artifacts:
      - build/**/*.app
