workflows:
  ios-simple-workflow:
    name: iOS Simple Workflow
    environment:
      xcode: 15.0  # Verifica la versión compatible de Xcode
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Instalar dependencias de CocoaPods (si es necesario)
        script: |
          if [ -e Podfile ]; then
            pod install
          fi
      - name: Compilar el Proyecto Sin Esquema
        script: |
          xcodebuild -project YourApp.xcodeproj \
                     -configuration Release \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
                     clean build
    artifacts:
      - build/**/*.app
